import { createSlice } from "@reduxjs/toolkit";

const initialState = {
    books: [
        {
            id: 1,
            title: "The Silent Patient",
            author: "Alex Michaelides",
            genre: "Thriller",
            year: 2019,
            description: "A psychological thriller about a woman who shoots her husband and then refuses to speak.",
            rating: 4.5,
        },
        {
            id: 2,
            title: "Educated",
            author: "Tara Westover",
            genre: "Biography",
            year: 2018,
            description: "A memoir about a woman who grows up in a survivalist family and later escapes to pursue education.",
            rating: 4.8,
        },
        {
            id: 3,
            title: "The Midnight Library",
            author: "Matt Haig",
            genre: "Fiction",
            year: 2020,
            description: "A story about a woman who discovers a library between life and death, where each book represents a different life she could have lived.",
            rating: 4.4,
        },
        {
            id: 4,
            title: "Dune",
            author: "Frank Herbert",
            genre: "Sci-Fi",
            year: 1965,
            description: "A science fiction epic set on the desert planet Arrakis, dealing with politics, religion, and ecology.",
            rating: 4.7,
        },
        {
            id: 5,
            title: "The Hobbit",
            author: "J.R.R. Tolkien",
            genre: "Fantasy",
            year: 1937,
            description: "The story of Bilbo Baggins' unexpected journey to recover a treasure guarded by the dragon Smaug.",
            rating: 4.9,
        },
        {
            id: 6,
            title: "Sapiens: A Brief History of Humankind",
            author: "Yuval Noah Harari",
            genre: "Non-fiction",
            year: 2011,
            description: "A compelling account of the history of the human race from the Stone Age to the present.",
            rating: 4.6,
        },
        {
            id: 7,
            title: "The Alchemist",
            author: "Paulo Coelho",
            genre: "Fiction",
            year: 1988,
            description: "A young shepherd named Santiago embarks on a journey to find treasure and his own personal legend.",
            rating: 4.8,
        },
        {
            id: 8,
            title: "The Girl on the Train",
            author: "Paula Hawkins",
            genre: "Thriller",
            year: 2015,
            description: "A psychological thriller centered around a woman who is deeply involved in a complex mystery after witnessing something suspicious on her daily train ride.",
            rating: 4.2,
        },
        {
            id: 9,
            title: "The Power of Habit",
            author: "Charles Duhigg",
            genre: "Self-help",
            year: 2012,
            description: "A book that explores the science behind habit formation and how we can change our habits to improve our lives.",
            rating: 4.3,
        },
        {
            id: 10,
            title: "The Subtle Art of Not Giving a F*ck",
            author: "Mark Manson",
            genre: "Self-help",
            year: 2016,
            description: "A self-help book that promotes embracing life’s challenges and focusing on the things that truly matter.",
            rating: 4.1,
        },
        {
            id: 11,
            title: "A Game of Thrones",
            author: "George R.R. Martin",
            genre: "Fantasy",
            year: 1996,
            description: "The first book in the 'A Song of Ice and Fire' series, full of political intrigue, war, and dragons.",
            rating: 4.7,
        },
        {
            id: 12,
            title: "Becoming",
            author: "Michelle Obama",
            genre: "Biography",
            year: 2018,
            description: "The memoir of former First Lady Michelle Obama, detailing her life, challenges, and experiences in the White House.",
            rating: 4.9,
        },
        {
            id: 13,
            title: "Atomic Habits",
            author: "James Clear",
            genre: "Self-help",
            year: 2018,
            description: "A practical guide to building good habits and breaking bad ones, with a focus on small, incremental changes.",
            rating: 4.8,
        },
        {
            id: 14,
            title: "The Night Circus",
            author: "Erin Morgenstern",
            genre: "Fantasy",
            year: 2011,
            description: "A novel about a magical circus and the competition between two young illusionists, set against a backdrop of mystery and romance.",
            rating: 4.5,
        },
        {
            id: 15,
            title: "The Hunger Games",
            author: "Suzanne Collins",
            genre: "Sci-Fi",
            year: 2008,
            description: "In a dystopian future, children from each district must fight to the death in a televised annual event known as the Hunger Games.",
            rating: 4.6,
        },
        {
            id: 16,
            title: "1984",
            author: "George Orwell",
            genre: "Sci-Fi",
            year: 1949,
            description: "A dystopian novel about a totalitarian regime that uses surveillance and mind control to keep its citizens under strict control.",
            rating: 4.8,
        },
        // Additional books I am adding:
        {
            id: 17,
            title: "Circe",
            author: "Madeline Miller",
            genre: "Fantasy",
            year: 2018,
            description: "A reimagining of the story of Circe, the enchantress from Greek mythology, told from her point of view.",
            rating: 4.7,
        },
        {
            id: 18,
            title: "The Book Thief",
            author: "Markus Zusak",
            genre: "Historical Fiction",
            year: 2005,
            description: "A story of a young girl in Nazi Germany, who steals books and shares them with others, while the world around her descends into war.",
            rating: 4.9,
        },
        {
            id: 19,
            title: "The Great Gatsby",
            author: "F. Scott Fitzgerald",
            genre: "Classic",
            year: 1925,
            description: "A novel about the American Dream and the disillusionment that comes with it, set during the Jazz Age in New York.",
            rating: 4.4,
        },
        {
            id: 20,
            title: "Where the Crawdads Sing",
            author: "Delia Owens",
            genre: "Mystery",
            year: 2018,
            description: "A mystery novel about a girl who grows up in the wild marshes of North Carolina and is suspected of killing a local man.",
            rating: 4.6,
        },
    ],
    searchQuery: "",
};

const booksSlice = createSlice({
    name: "books",
    initialState,
    reducers: {
        setSearchQuery: (state, action) => {
            state.searchQuery = action.payload;
        },
        addBook: (state, action) => {
            state.books.push(action.payload);
        },
    },
});

export const { setSearchQuery, addBook } = booksSlice.actions;

export default booksSlice.reducer;
